CREATE TABLE CAF_ACCOUNT (
    ID          VARCHAR2(20)
    ,PW         VARCHAR2(20)
    ,NAME       VARCHAR2(20)
    ,NICKNAME   VARCHAR2(20)
    ,EMAIL      VARCHAR2(50)    PRIMARY KEY
);

CREATE TABLE CAF_POST (
    NUM         NUMBER(5)
    ,TITLE      VARCHAR2(20)
    ,WRITER     VARCHAR2(20)
    ,POST_DATE  DATE
    ,CONTENT    VARCHAR2(20)
    ,PICTURE    VARCHAR2(20)
    ,EMAIL      VARCHAR2(50)
    ,CONSTRAINT ACCOUNT_ORDER_FK FOREIGN KEY( EMAIL ) REFERENCES CAF_ACCOUNT( EMAIL )
);

DROP TABLE CAF_DRINK;

SELECT  *
FROM    CAF_ACCOUNT;


INSERT INTO CAF_ACCOUNT
VALUES ('hanji', '0403', 'วัม๖ฟฌ', 'HanjiHanji', 'hanji0403@naver.com');

COMMIT;